server:
    context-path: /workflow/api
    port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2console
      settings:
        trace: true
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:activitidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    